import { useMemo, useState } from 'react'
import type { Language, NotationMode } from '../i18n'
import { DepthNote } from './DepthNote'
import { ApplicationLinks } from './ApplicationLinks'

type Props={notation:NotationMode;language:Language;onBack?:()=>void}
const text={
ru:{title:'Ogden: гиперупругость через главные растяжения',lead:'Модель Ogden строит энергию напрямую через главные растяжения λ₁, λ₂, λ₃. Это делает её гибкой для описания сильной нелинейности, особенно когда простые инвариантные модели уже недостаточны.',key:'ПАРАМЕТР α УПРАВЛЯЕТ ФОРМОЙ НЕЛИНЕЙНОГО ОТКЛИКА',keyText:'При α = 2 однопараметрическая несжимаемая модель Ogden совпадает по форме с Neo-Hookean. При других α кривизна stress–stretch существенно меняется.',model:'Одночленная модель Ogden',modelText:'Для несжимаемого материала Ψ = 2μ/α²(λ₁^α+λ₂^α+λ₃^α−3). В одноосном растяжении λ₂=λ₃=λ⁻¹ᐟ².',why:'Почему это полезно',whyText:'Главные растяжения позволяют задавать нелинейность спектрально и расширять модель несколькими членами с разными μₚ и αₚ.',lambda:'растяжение λ',mu:'μ',alpha:'α',energy:'Ψ',stress:'P',sceneKicker:'OGDEN EXPLORER',sceneTitle:'меняй α и смотри, как перестраивается нелинейный отклик',checkpoint:'ВОПРОС ДЛЯ ПРОВЕРКИ',checkpointTitle:'Что особенного в α = 2?',checkpointText:'В однопараметрической несжимаемой форме Ogden при α = 2 энергия сводится к Neo-Hookean по зависимости от главных растяжений.',conclusion:'ВЫВОД',conclusionTitle:'Ogden даёт более гибкое семейство, чем одна зависимость от I₁.',conclusionText:'Следующий шаг — отделить объёмный и изохорный вклад и корректно работать с почти несжимаемыми материалами.',deepen:'Углубиться',deepenText:'Многопараметрическая форма Ψ = Σₚ 2μₚ/αₚ²(λ₁^{αₚ}+λ₂^{αₚ}+λ₃^{αₚ}−3) позволяет аппроксимировать широкий спектр нелинейных кривых.',research:'Исследовательское замечание',researchText:'Гибкость Ogden усиливает проблему идентифицируемости: несколько пар μₚ, αₚ могут давать похожие кривые в одном эксперименте. Нужны многорежимные данные и регуляризация.',warning:'ВАЖНО',warningTitle:'Сильная гибкость модели требует аккуратной калибровки.',warningText:'Неудачные параметры могут давать нефизичные кривые вне диапазона данных, особенно при экстраполяции в сильное сжатие или растяжение.',back:'← D04',interactive:'ИНТЕРАКТИВНО'},
en:{title:'Ogden: hyperelasticity through principal stretches',lead:'The Ogden model expresses energy directly through principal stretches λ₁, λ₂, λ₃. This gives it substantial flexibility for strongly nonlinear response.',key:'THE PARAMETER α CONTROLS THE SHAPE OF NONLINEAR RESPONSE',keyText:'For α = 2, the one-term incompressible Ogden model has the same stretch dependence as Neo-Hookean. Other α values strongly alter curvature.',model:'One-term Ogden model',modelText:'For an incompressible material Ψ = 2μ/α²(λ₁^α+λ₂^α+λ₃^α−3). In uniaxial tension λ₂=λ₃=λ⁻¹ᐟ².',why:'Why it is useful',whyText:'Principal stretches provide a spectral description of nonlinearity and naturally extend to multiple terms with different μₚ and αₚ.',lambda:'stretch λ',mu:'μ',alpha:'α',energy:'Ψ',stress:'P',sceneKicker:'OGDEN EXPLORER',sceneTitle:'vary α and watch the nonlinear response change',checkpoint:'CHECKPOINT',checkpointTitle:'What is special about α = 2?',checkpointText:'In the one-term incompressible Ogden model, α = 2 reduces to the Neo-Hookean stretch dependence.',conclusion:'CONCLUSION',conclusionTitle:'Ogden provides a more flexible family than a single I₁ dependence.',conclusionText:'Next we separate volumetric and isochoric contributions and handle nearly incompressible materials correctly.',deepen:'Go deeper',deepenText:'The multi-term form Ψ = Σₚ 2μₚ/αₚ²(λ₁^{αₚ}+λ₂^{αₚ}+λ₃^{αₚ}−3) can approximate a wide range of nonlinear curves.',research:'Research note',researchText:'Ogden flexibility increases identifiability challenges: several μₚ, αₚ combinations may fit one experiment similarly. Multi-mode data and regularization become important.',warning:'IMPORTANT',warningTitle:'High flexibility requires careful calibration.',warningText:'Poor parameter choices can produce nonphysical extrapolation, especially in large compression or extension.',back:'← D04',interactive:'INTERACTIVE'}
} as const
function fmt(v:number,d=3){return (Math.abs(v)<1e-12?0:v).toFixed(d)}
function psi(l:number,mu:number,a:number){return 2*mu/(a*a)*(Math.pow(l,a)+2*Math.pow(l,-a/2)-3)}
function P(l:number,mu:number,a:number){const h=1e-5;return (psi(l+h,mu,a)-psi(Math.max(.35,l-h),mu,a))/(2*h)}
export function OgdenModel({notation,language,onBack}:Props){
 const copy=text[language]; const [lambda,setLambda]=useState(1.3); const [mu,setMu]=useState(20); const [alpha,setAlpha]=useState(2)
 const data=useMemo(()=>({psi:psi(lambda,mu,alpha),p:P(lambda,mu,alpha),pNH:P(lambda,mu,2)}),[lambda,mu,alpha])
 const formula=notation==='Python'?'W = 2*mu/alpha**2*(l1**alpha+l2**alpha+l3**alpha-3)':notation==='Index'?'Ψ = 2μ/α² Σᵢ(λᵢ^α−1)':'Ψ = 2μ/α²(λ₁^α+λ₂^α+λ₃^α−3)'
 const curve=Array.from({length:101},(_,i)=>{const l=.6+i*1.1/100;return {l,p:P(l,mu,alpha),n:P(l,mu,2)}})
 const vals=curve.flatMap(x=>[x.p,x.n]); const ymin=Math.min(...vals,0), ymax=Math.max(...vals,0), span=Math.max(ymax-ymin,1e-6)
 const path=(k:'p'|'n')=>curve.map((q,i)=>{const x=8+(q.l-.6)/1.1*84;const y=52-(q[k]-ymin)/span*39;return `${i?'L':'M'} ${x.toFixed(2)} ${y.toFixed(2)}`}).join(' ')
 return <section className="module-view module-view-stacked"><div className="lesson-copy">
 <div className="lesson-index">D05</div><h1>{copy.title}</h1><p className="lead">{copy.lead}</p>
 <div className="concept-card"><span>{copy.key}</span><strong>{copy.keyText}</strong></div>
 <div className="definition"><div className="definition-label">{copy.model}</div><div className="formula">{formula}</div><p>{copy.modelText}</p></div>
 <div className="definition"><div className="definition-label">{copy.why}</div><p>{copy.whyText}</p></div>
 <div className="warning-card kinematics-warning"><span>{copy.warning}</span><strong>{copy.warningTitle}</strong><p>{copy.warningText}</p></div>
 <DepthNote label={copy.deepen}><p>{copy.deepenText}</p></DepthNote><DepthNote label={copy.research} variant="research"><p>{copy.researchText}</p></DepthNote>
 <ApplicationLinks language={language} items={[{ru:'Эластомеры',en:'Elastomers'},{ru:'Мягкие ткани',en:'Soft tissues'},{ru:'Inverse modeling',en:'Inverse modeling'},{ru:'Нелинейный FEM',en:'Nonlinear FEM'}]}/>
 {onBack&&<button className="text-button" onClick={onBack}>{copy.back}</button>}
 </div><div className="scene-column"><div className="scene-card"><div className="scene-head"><div><span className="scene-kicker">{copy.sceneKicker}</span><h2>{copy.sceneTitle}</h2></div><div className="live-badge">{copy.interactive}</div></div>
 <svg className="balance-scene" viewBox="0 0 100 60"><rect x="5" y="5" width="90" height="50" rx="8" fill="#111318"/><line x1="8" y1="52" x2="94" y2="52" stroke="#69717C" strokeWidth=".6"/><line x1="8" y1="52" x2="8" y2="10" stroke="#69717C" strokeWidth=".6"/><path d={path('n')} fill="none" stroke="#2864FF" strokeWidth="1.2"/><path d={path('p')} fill="none" stroke="#A9E3D2" strokeWidth="1.4"/><text x="10" y="13" fill="#2864FF" fontSize="2.2">α=2</text><text x="10" y="17" fill="#A9E3D2" fontSize="2.2">α={fmt(alpha,1)}</text></svg>
 <div className="control-stack"><label><span>{copy.lambda}<strong>{fmt(lambda,2)}</strong></span><input type="range" min=".6" max="1.7" step=".01" value={lambda} onChange={e=>setLambda(Number(e.target.value))}/></label><label><span>{copy.mu}<strong>{fmt(mu,1)}</strong></span><input type="range" min="2" max="60" step="1" value={mu} onChange={e=>setMu(Number(e.target.value))}/></label><label><span>{copy.alpha}<strong>{fmt(alpha,1)}</strong></span><input type="range" min="-4" max="8" step=".1" value={alpha} onChange={e=>{const v=Number(e.target.value);setAlpha(Math.abs(v)<.2?(v<0?-.2:.2):v)}}/></label></div>
 <div className="transport-metrics"><div><span>{copy.energy}</span><strong>{fmt(data.psi)}</strong></div><div><span>{copy.stress}</span><strong>{fmt(data.p)}</strong></div><div><span>ΔP vs α=2</span><strong>{fmt(data.p-data.pNH)}</strong></div></div>
 </div><div className="bottom-grid"><div className="prediction-card"><span>{copy.checkpoint}</span><strong>{copy.checkpointTitle}</strong><p>{copy.checkpointText}</p></div><div className="author-card"><span>{copy.conclusion}</span><strong>{copy.conclusionTitle}</strong><p>{copy.conclusionText}</p></div></div></div></section>
}